In [1]:
# Import Libraries
import pandas as pd 
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [4]:
# Load DATA 
df = pd.read_csv('dataset.csv')

In [5]:
df.head()

label      1      2         3         4         5         6         7  \
0  angry  292.0  209.0  1.032806  0.000515  0.941451  0.423294  0.274058   
1  angry   61.0  227.0  1.026659 -0.000546  1.117848  0.431065  0.309706   
2  angry  124.0   95.0  1.097458  0.001754  0.923793  0.537061  0.411795   
3  angry   62.0   79.0  0.985723 -0.003297  1.419296  0.606357  0.606616   
4  angry   63.0  222.0  1.025019 -0.001701  1.271647  0.720588  0.718868   

          8         9  ...      1574      1575      1576      1577      1578  \
0  0.526171  1.267252  ...  0.000117  0.000297  0.000137  0.000434  0.006980   
1  0.559012  1.777863  ...  0.000127  0.000162  0.000124  0.000286  0.003999   
2  0.649577  1.170659  ...  0.000147  0.000242  0.000162  0.000404  0.057374   
3  0.818385  1.609624  ...  0.000204  0.000195  0.000194  0.000389  0.007055   
4  0.859816  0.963838  ...  0.000118  0.000162  0.000120  0.000281  0.001605   

       1579      1580      1581  1582  1583  
0  0.826816  0.011173  3.351955  3.58     0  
1  0.938889  0.005556  1.483680  3.37     0  
2  0.010753  0.010753  0.995025  2.01     0  
3  0.006944  0.006944  2.255639  2.66     0  
4  0.006579  0.006579  1.365188  2.93     0  

[5 rows x 1584 columns]

In [6]:
df.shape

(480, 1584)

In [7]:
df.describe()

1           2           3           4           5           6  \
count  480.000000  480.000000  480.000000  480.000000  480.000000  480.000000   
mean   142.054167  212.047917    0.733936   -0.000204    0.772491    0.333233   
std     91.515569  109.131606    0.362403    0.000689    0.386215    0.245509   
min     28.000000   31.000000    0.118577   -0.003297    0.107882    0.037067   
25%     74.000000  123.750000    0.477854   -0.000414    0.447192    0.121439   
50%    106.000000  198.500000    0.794544   -0.000157    0.830099    0.265324   
75%    190.000000  285.250000    0.992477    0.000021    1.027935    0.505518   
max    485.000000  563.000000    1.741387    0.007161    1.757577    1.111566   

                7           8           9          10  ...        1574  \
count  480.000000  480.000000  480.000000  480.000000  ...  480.000000   
mean     0.257060    0.419496    1.490876    5.138977  ...    0.000127   
std      0.307991    0.292476    0.448059    2.108096  ...    0.000072   
min      0.002307    0.054395   -0.071583    1.885526  ...    0.000014   
25%      0.024782    0.161515    1.184744    3.632809  ...    0.000079   
50%      0.117951    0.347121    1.474774    4.650827  ...    0.000109   
75%      0.397464    0.631760    1.777627    6.240841  ...    0.000153   
max      1.640258    1.280760    3.160062   14.015520  ...    0.000657   

             1575        1576        1577        1578        1579        1580  \
count  480.000000  480.000000  480.000000  480.000000  480.000000  480.000000   
mean     0.000234    0.000144    0.000378    0.005133    0.508014    0.312048   
std      0.000164    0.000082    0.000227    0.007643    0.470435    0.425028   
min      0.000042    0.000041    0.000086    0.000386    0.002786    0.002558   
25%      0.000136    0.000089    0.000233    0.001455    0.009938    0.006536   
50%      0.000192    0.000122    0.000322    0.002545    0.805317    0.012579   
75%      0.000274    0.000174    0.000448    0.004986    0.972863    0.893684   
max      0.001365    0.000686    0.001816    0.057374    0.993103    0.989474   

             1581        1582        1583  
count  480.000000  480.000000  480.000000  
mean     2.426308    3.774604    3.125000  
std      0.771399    1.077901    1.901818  
min      0.381679    1.570000    0.000000  
25%      1.947150    3.015000    1.750000  
50%      2.400000    3.605000    3.500000  
75%      2.917772    4.452500    4.250000  
max      5.000000    7.070000    6.000000  

[8 rows x 1583 columns]

In [8]:
df.label.unique()

array(['angry', 'disgust', 'fear', 'happiness', 'neutral', 'sadness',
       'surprise'], dtype=object)

In [9]:
# Header for Features without Labels 
features = [str(i) for i in range(1,1583)]

In [10]:
# Standarize the DATA 
X = df.loc[:,features].values

Y = df.loc[:,'label'].values

In [11]:
X

array([[2.920000e+02, 2.090000e+02, 1.032806e+00, ..., 1.117318e-02,
        3.351955e+00, 3.580000e+00],
       [6.100000e+01, 2.270000e+02, 1.026659e+00, ..., 5.555556e-03,
        1.483680e+00, 3.370000e+00],
       [1.240000e+02, 9.500000e+01, 1.097458e+00, ..., 1.075269e-02,
        9.950249e-01, 2.010000e+00],
       ...,
       [8.500000e+01, 3.070000e+02, 1.886774e-01, ..., 5.000000e-03,
        2.305475e+00, 3.470000e+00],
       [8.200000e+01, 3.450000e+02, 1.763397e-01, ..., 3.703704e-03,
        2.884615e+00, 5.200000e+00],
       [1.160000e+02, 9.100000e+01, 1.751087e-01, ..., 3.194888e-03,
        2.936097e+00, 5.790000e+00]])

In [12]:
Y

array(['angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry',
       'angry', 'angry', 'angry', 'angry', 'angry', 'angry', 'angry',
       'angry', 'disgust', 'disgust', 'disgust', 'disgust', 'disgust',
       'disgust', 'disgust', 'disgust', 'disgust', 'disgust', 'disgust',
       'disgust', 'disgust', 'disgust', 'disgust', 'fear', 'fear', 'fear',
       'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear', 'fear',
       'fear', 'fear', 'fear', 'fear', 'happiness', 'happiness',
       'happiness', 'happiness', 'happiness', 'happiness', 'happiness',
       'happiness', 'happiness', 'happiness', 'happiness', 'happiness',
       'happiness', 'happiness', 'happiness', 'neutral', 'neutral',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
 

In [13]:
X = StandardScaler().fit_transform(X)

In [14]:
X

array([[ 1.6401829 , -0.02795796,  0.82554925, ..., -0.70863285,
         1.20121021, -0.18072836],
       [-0.88661122,  0.13715259,  0.8085698 , ..., -0.7218637 ,
        -1.2232467 , -0.37575479],
       [-0.19748555, -1.07365809,  1.00413323, ..., -0.70962321,
        -1.85737349, -1.63878309],
       ...,
       [-0.62408716,  0.87097725, -1.50613185, ..., -0.72317217,
        -0.15680489, -0.28288506],
       [-0.65690266,  1.21954396, -1.54021147, ..., -0.72622526,
         0.59474398,  1.32376123],
       [-0.28499357, -1.11034933, -1.54361178, ..., -0.72742364,
         0.66155207,  1.87169263]])

In [15]:
# PCA  
# n : Number of principal components 
n = 90
pca = PCA(n_components = n)

In [16]:
pca

PCA(n_components=90)

In [17]:
X = pca.fit_transform(X)

In [18]:
len(X[0])

90

In [19]:
#Split data to train and test 
X_train, X_test, Y_train, Y_test = train_test_split (X,Y,test_size=0.2)

In [20]:
#Create a Multi-Layer Classifier instance 
classifier = MLPClassifier(alpha=1.9,max_iter=700)

In [21]:
#Fit the classifier
classifier.fit(X_train,Y_train)

MLPClassifier(alpha=1.9, max_iter=700)

In [22]:
#Calculate the score (Accuracy)
score = classifier.score(X_test,Y_test)

In [23]:
print(classifier.classes_)

['angry' 'disgust' 'fear' 'happiness' 'neutral' 'sadness' 'surprise']


In [24]:
#Printing the score
print("score - test", score)

score - test 0.71875


In [25]:
score_train = classifier.score(X_train,Y_train)

In [26]:
#Printing the score
print("score - train", score_train)

score - train 1.0


In [27]:
y_pred = classifier.predict(X_test)

In [28]:
y_pred

array(['sadness', 'angry', 'neutral', 'neutral', 'disgust', 'neutral',
       'happiness', 'surprise', 'fear', 'neutral', 'fear', 'sadness',
       'surprise', 'disgust', 'sadness', 'sadness', 'neutral', 'surprise',
       'fear', 'neutral', 'neutral', 'fear', 'fear', 'neutral', 'disgust',
       'surprise', 'happiness', 'neutral', 'angry', 'neutral',
       'happiness', 'happiness', 'neutral', 'sadness', 'happiness',
       'neutral', 'angry', 'sadness', 'surprise', 'fear', 'sadness',
       'surprise', 'fear', 'happiness', 'angry', 'surprise', 'fear',
       'happiness', 'happiness', 'surprise', 'disgust', 'neutral',
       'angry', 'neutral', 'surprise', 'sadness', 'angry', 'fear',
       'happiness', 'happiness', 'fear', 'angry', 'happiness', 'neutral',
       'sadness', 'angry', 'happiness', 'neutral', 'angry', 'neutral',
       'neutral', 'sadness', 'neutral', 'fear', 'angry', 'sadness',
       'neutral', 'disgust', 'fear', 'neutral', 'sadness', 'angry',
       'neutral', 'fear',

In [29]:
# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(Y_test, y_pred))

Confusion Matrix:
[[ 9  0  0  4  0  0  1]
 [ 0  5  1  0  2  2  0]
 [ 0  0 10  1  0  2  2]
 [ 1  0  1 10  0  0  0]
 [ 0  1  0  0 20  3  0]
 [ 0  0  1  0  2  7  0]
 [ 1  0  1  1  0  0  8]]


In [30]:
# Classification result
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

       angry       0.82      0.64      0.72        14
     disgust       0.83      0.50      0.62        10
        fear       0.71      0.67      0.69        15
   happiness       0.62      0.83      0.71        12
     neutral       0.83      0.83      0.83        24
     sadness       0.50      0.70      0.58        10
    surprise       0.73      0.73      0.73        11

    accuracy                           0.72        96
   macro avg       0.72      0.70      0.70        96
weighted avg       0.74      0.72      0.72        96



In [35]:
import subprocess

# Define paths
opensmile_path = r"C:\opensmile-3.0-win-x64\bin\SMILExtract.exe"  # Path to the OpenSMILE executable
config_file = r"C:\opensmile-3.0-win-x64\config\is09-13\IS10_paraling_compat.conf"  # Path to the configuration file
input_wav = r"D:\VocalCoach\Emotion\EmotionGithub\Test\angry.wav"  # Path to the input wav file
output_csv = r"D:\VocalCoach\Emotion\EmotionGithub\result\output_feature.arff"  # Path to save the output feature CSV

# Command to execute OpenSMILE
command = [
    opensmile_path,
    "-C", config_file,          # Configuration file
    "-I", input_wav,            # Input .wav file
    "-O", output_csv            # Output CSV file
]

# Execute the command
subprocess.run(command)


CompletedProcess(args=['C:\\opensmile-3.0-win-x64\\bin\\SMILExtract.exe', '-C', 'C:\\opensmile-3.0-win-x64\\config\\is09-13\\IS10_paraling_compat.conf', '-I', 'D:\\VocalCoach\\Emotion\\EmotionGithub\\Test\\angry.wav', '-O', 'D:\\VocalCoach\\Emotion\\EmotionGithub\\result\\output_feature.arff'], returncode=0)

In [40]:
import pandas as pd
import arff  # This comes from the liac-arff library

# Path to the ARFF file
arff_file = r"D:\\VocalCoach\\Emotion\\EmotionGithub\\result\\output_feature.arff"

# Read ARFF file
with open(arff_file, 'r') as file:
    arff_data = arff.load(file)

# Extract the data and column names
data = arff_data['data']
column_names = [attr[0] for attr in arff_data['attributes']]

# Convert to a pandas DataFrame
df = pd.DataFrame(data, columns=column_names)

# Save to CSV
# csv_file = r"D:\path\to\your\file.csv"
# df.to_csv(csv_file, index=False)

# print(f"ARFF data successfully converted to {csv_file}")


In [42]:
df.head()

name  pcm_loudness_sma_maxPos  pcm_loudness_sma_minPos  \
0  unknown                    188.0                      4.0   

   pcm_loudness_sma_amean  pcm_loudness_sma_linregc1  \
0                0.538449                  -0.000163   

   pcm_loudness_sma_linregc2  pcm_loudness_sma_linregerrA  \
0                    0.56206                     0.360393   

   pcm_loudness_sma_linregerrQ  pcm_loudness_sma_stddev  \
0                     0.185502                 0.430917   

   pcm_loudness_sma_skewness  ...  shimmerLocal_sma_de_quartile3  \
0                   0.593584  ...                       0.017249   

   shimmerLocal_sma_de_iqr1-2  shimmerLocal_sma_de_iqr2-3  \
0                    0.021283                    0.019546   

   shimmerLocal_sma_de_iqr1-3  shimmerLocal_sma_de_percentile99.0  \
0                    0.040829                            0.147674   

   shimmerLocal_sma_de_upleveltime75  shimmerLocal_sma_de_upleveltime90  \
0                           0.019737                           0.006579   

   F0final__Turn_numOnsets  F0final__Turn_duration  class  
0                     13.0                    2.92   None  

[1 rows x 1584 columns]

In [43]:
df.columns

Index(['name', 'pcm_loudness_sma_maxPos', 'pcm_loudness_sma_minPos',
       'pcm_loudness_sma_amean', 'pcm_loudness_sma_linregc1',
       'pcm_loudness_sma_linregc2', 'pcm_loudness_sma_linregerrA',
       'pcm_loudness_sma_linregerrQ', 'pcm_loudness_sma_stddev',
       'pcm_loudness_sma_skewness',
       ...
       'shimmerLocal_sma_de_quartile3', 'shimmerLocal_sma_de_iqr1-2',
       'shimmerLocal_sma_de_iqr2-3', 'shimmerLocal_sma_de_iqr1-3',
       'shimmerLocal_sma_de_percentile99.0',
       'shimmerLocal_sma_de_upleveltime75',
       'shimmerLocal_sma_de_upleveltime90', 'F0final__Turn_numOnsets',
       'F0final__Turn_duration', 'class'],
      dtype='object', length=1584)

In [45]:
df.pop("name")

0    unknown
Name: name, dtype: object

In [48]:
df.pop("class")

0    None
Name: class, dtype: object

In [60]:
df.head()

pcm_loudness_sma_maxPos  pcm_loudness_sma_minPos  pcm_loudness_sma_amean  \
0                    188.0                      4.0                0.538449   

   pcm_loudness_sma_linregc1  pcm_loudness_sma_linregc2  \
0                  -0.000163                    0.56206   

   pcm_loudness_sma_linregerrA  pcm_loudness_sma_linregerrQ  \
0                     0.360393                     0.185502   

   pcm_loudness_sma_stddev  pcm_loudness_sma_skewness  \
0                 0.430917                   0.593584   

   pcm_loudness_sma_kurtosis  ...  shimmerLocal_sma_de_quartile2  \
0                   2.632063  ...                      -0.002297   

   shimmerLocal_sma_de_quartile3  shimmerLocal_sma_de_iqr1-2  \
0                       0.017249                    0.021283   

   shimmerLocal_sma_de_iqr2-3  shimmerLocal_sma_de_iqr1-3  \
0                    0.019546                    0.040829   

   shimmerLocal_sma_de_percentile99.0  shimmerLocal_sma_de_upleveltime75  \
0                            0.147674                           0.019737   

   shimmerLocal_sma_de_upleveltime90  F0final__Turn_numOnsets  \
0                           0.006579                     13.0   

   F0final__Turn_duration  
0                    2.92  

[1 rows x 1582 columns]

In [49]:
df.columns

Index(['pcm_loudness_sma_maxPos', 'pcm_loudness_sma_minPos',
       'pcm_loudness_sma_amean', 'pcm_loudness_sma_linregc1',
       'pcm_loudness_sma_linregc2', 'pcm_loudness_sma_linregerrA',
       'pcm_loudness_sma_linregerrQ', 'pcm_loudness_sma_stddev',
       'pcm_loudness_sma_skewness', 'pcm_loudness_sma_kurtosis',
       ...
       'shimmerLocal_sma_de_quartile2', 'shimmerLocal_sma_de_quartile3',
       'shimmerLocal_sma_de_iqr1-2', 'shimmerLocal_sma_de_iqr2-3',
       'shimmerLocal_sma_de_iqr1-3', 'shimmerLocal_sma_de_percentile99.0',
       'shimmerLocal_sma_de_upleveltime75',
       'shimmerLocal_sma_de_upleveltime90', 'F0final__Turn_numOnsets',
       'F0final__Turn_duration'],
      dtype='object', length=1582)

In [51]:
df.shape

(1, 1582)

In [74]:
df

pcm_loudness_sma_maxPos  pcm_loudness_sma_minPos  pcm_loudness_sma_amean  \
0                    188.0                      4.0                0.538449   

   pcm_loudness_sma_linregc1  pcm_loudness_sma_linregc2  \
0                  -0.000163                    0.56206   

   pcm_loudness_sma_linregerrA  pcm_loudness_sma_linregerrQ  \
0                     0.360393                     0.185502   

   pcm_loudness_sma_stddev  pcm_loudness_sma_skewness  \
0                 0.430917                   0.593584   

   pcm_loudness_sma_kurtosis  ...  shimmerLocal_sma_de_quartile2  \
0                   2.632063  ...                      -0.002297   

   shimmerLocal_sma_de_quartile3  shimmerLocal_sma_de_iqr1-2  \
0                       0.017249                    0.021283   

   shimmerLocal_sma_de_iqr2-3  shimmerLocal_sma_de_iqr1-3  \
0                    0.019546                    0.040829   

   shimmerLocal_sma_de_percentile99.0  shimmerLocal_sma_de_upleveltime75  \
0                            0.147674                           0.019737   

   shimmerLocal_sma_de_upleveltime90  F0final__Turn_numOnsets  \
0                           0.006579                     13.0   

   F0final__Turn_duration  
0                    2.92  

[1 rows x 1582 columns]

In [54]:
# input_test = df.loc[:,features].values
input_test = StandardScaler().fit_transform(df)

In [79]:
input_test.shape

(1, 1582)

In [80]:
arr_subset = input_test[:, :90]

In [81]:
classifier.predict(arr_subset)

array(['disgust'], dtype='<U9')

In [57]:
input_test_pca= pca.fit_transform(input_test)

ValueError: n_components=90 must be between 0 and min(n_samples, n_features)=1 with svd_solver='full'

In [63]:
new_features_pca= df.iloc[0].to_list()

In [65]:
# Convert the list to a numpy array
new_features_array = np.array(new_features_pca).astype(float)  # Convert to float if necessary

# Reshape to a 2D array with 1 row and n columns (1500 features in this case)
new_features_array = new_features_array.reshape(1, -1)

# Step 1: Standardize the input features (if necessary)
new_features_scaled = StandardScaler().transform(new_features_array)


# Step 2: Apply PCA transformation (if PCA was used during training)
# new_features_pca = pca.transform(new_features_scaled)

NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.