In [1]:
import pandas as pd 
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [7]:
# Load DATA 
df = pd.read_csv('Classifiers\dataset.csv')
df.head()

label      1      2         3         4         5         6         7  \
0  angry  292.0  209.0  1.032806  0.000515  0.941451  0.423294  0.274058   
1  angry   61.0  227.0  1.026659 -0.000546  1.117848  0.431065  0.309706   
2  angry  124.0   95.0  1.097458  0.001754  0.923793  0.537061  0.411795   
3  angry   62.0   79.0  0.985723 -0.003297  1.419296  0.606357  0.606616   
4  angry   63.0  222.0  1.025019 -0.001701  1.271647  0.720588  0.718868   

          8         9  ...      1574      1575      1576      1577      1578  \
0  0.526171  1.267252  ...  0.000117  0.000297  0.000137  0.000434  0.006980   
1  0.559012  1.777863  ...  0.000127  0.000162  0.000124  0.000286  0.003999   
2  0.649577  1.170659  ...  0.000147  0.000242  0.000162  0.000404  0.057374   
3  0.818385  1.609624  ...  0.000204  0.000195  0.000194  0.000389  0.007055   
4  0.859816  0.963838  ...  0.000118  0.000162  0.000120  0.000281  0.001605   

       1579      1580      1581  1582  1583  
0  0.826816  0.011173  3.351955  3.58     0  
1  0.938889  0.005556  1.483680  3.37     0  
2  0.010753  0.010753  0.995025  2.01     0  
3  0.006944  0.006944  2.255639  2.66     0  
4  0.006579  0.006579  1.365188  2.93     0  

[5 rows x 1584 columns]

In [8]:
df.label.unique()

array(['angry', 'disgust', 'fear', 'happiness', 'neutral', 'sadness',
       'surprise'], dtype=object)

In [5]:
df.describe()

1           2           3           4           5           6  \
count  480.000000  480.000000  480.000000  480.000000  480.000000  480.000000   
mean   142.054167  212.047917    0.733936   -0.000204    0.772491    0.333233   
std     91.515569  109.131606    0.362403    0.000689    0.386215    0.245509   
min     28.000000   31.000000    0.118577   -0.003297    0.107882    0.037067   
25%     74.000000  123.750000    0.477854   -0.000414    0.447192    0.121439   
50%    106.000000  198.500000    0.794544   -0.000157    0.830099    0.265324   
75%    190.000000  285.250000    0.992477    0.000021    1.027935    0.505518   
max    485.000000  563.000000    1.741387    0.007161    1.757577    1.111566   

                7           8           9          10  ...        1574  \
count  480.000000  480.000000  480.000000  480.000000  ...  480.000000   
mean     0.257060    0.419496    1.490876    5.138977  ...    0.000127   
std      0.307991    0.292476    0.448059    2.108096  ...    0.000072   
min      0.002307    0.054395   -0.071583    1.885526  ...    0.000014   
25%      0.024782    0.161515    1.184744    3.632809  ...    0.000079   
50%      0.117951    0.347121    1.474774    4.650827  ...    0.000109   
75%      0.397464    0.631760    1.777627    6.240841  ...    0.000153   
max      1.640258    1.280760    3.160062   14.015520  ...    0.000657   

             1575        1576        1577        1578        1579        1580  \
count  480.000000  480.000000  480.000000  480.000000  480.000000  480.000000   
mean     0.000234    0.000144    0.000378    0.005133    0.508014    0.312048   
std      0.000164    0.000082    0.000227    0.007643    0.470435    0.425028   
min      0.000042    0.000041    0.000086    0.000386    0.002786    0.002558   
25%      0.000136    0.000089    0.000233    0.001455    0.009938    0.006536   
50%      0.000192    0.000122    0.000322    0.002545    0.805317    0.012579   
75%      0.000274    0.000174    0.000448    0.004986    0.972863    0.893684   
max      0.001365    0.000686    0.001816    0.057374    0.993103    0.989474   

             1581        1582        1583  
count  480.000000  480.000000  480.000000  
mean     2.426308    3.774604    3.125000  
std      0.771399    1.077901    1.901818  
min      0.381679    1.570000    0.000000  
25%      1.947150    3.015000    1.750000  
50%      2.400000    3.605000    3.500000  
75%      2.917772    4.452500    4.250000  
max      5.000000    7.070000    6.000000  

[8 rows x 1583 columns]

In [6]:
df.shape

(480, 1584)

In [11]:

# Header for Features without Labels 
features = [str(i) for i in range(1,1583)]

In [12]:
# Standarize the DATA 
X = df.loc[:,features].values

Y = df.loc[:,'label'].values

In [15]:
X = StandardScaler().fit_transform(X)

# PCA  
# n : Number of principal components 
n = 90
pca = PCA(n_components = n)

X = pca.fit_transform(X)

In [19]:
#Split data to train and test 
X_train, X_test, Y_train, Y_test = train_test_split (X,Y,test_size=0.2)

#Create a Multi-Layer Classifier instance 
classifier = MLPClassifier(alpha=1.9,max_iter=700)

In [21]:
#Fit the classifier
classifier.fit(X_train,Y_train)

MLPClassifier(alpha=1.9, max_iter=700)

In [26]:
#Calculate the score (Accuracy) - Testing
score = classifier.score(X_test,Y_test)

In [24]:
print(classifier.classes_)

['angry' 'disgust' 'fear' 'happiness' 'neutral' 'sadness' 'surprise']


In [25]:
#Printing the score
print("Testing", score)

Testing 0.7291666666666666


In [27]:
#Calculate the score (Accuracy) - Training
score = classifier.score(X_train,Y_train)

In [28]:
print("Training", score)

Training 1.0


In [29]:
from sklearn.metrics import classification_report

# Predict on the test set
Y_pred = classifier.predict(X_test)


In [30]:
# Print classification report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

       angry       0.85      0.61      0.71        18
     disgust       0.67      0.62      0.64        13
        fear       0.57      0.67      0.62         6
   happiness       0.64      0.82      0.72        11
     neutral       0.81      0.96      0.88        23
     sadness       0.70      0.54      0.61        13
    surprise       0.69      0.75      0.72        12

    accuracy                           0.73        96
   macro avg       0.70      0.71      0.70        96
weighted avg       0.73      0.73      0.72        96



In [ ]:
# Load DATA 
testdfangry = pd.read_excel('Test\Book1.csv')
# testdfangry = pd.read_csv('Test\angry.csv')""
testdfangry.head()

In [96]:
df = pd.read_csv('Test\Book1.csv', delimiter=';', encoding='utf-8', header= None)  # or sep=';'


In [100]:
df

0
0  1.88E+02,4.00E+00,5.38E-01,-1.63E-04,5.62E-01,...
1  7.80E+01,1.98E+02,3.29E-01,-7.19E-04,4.02E-01,...
2  2.80E+02,3.19E+02,3.37E-01,-1.96E-04,3.70E-01,...
3  2.27E+02,7.00E+00,2.95E-01,3.25E-04,2.45E-01,2...
4  1.85E+02,2.08E+02,6.12E-01,1.50E-04,5.95E-01,4...

In [97]:
df.shape

(5, 1)

In [104]:
# Split the comma-separated strings into lists of values
df_expanded = df[0].str.split(',', expand=True)

# Convert to a DataFrame with the correct shape
df_expanded = pd.DataFrame(df_expanded.values, columns=[f'feature_{i}' for i in range(df_expanded.shape[1])])

In [107]:
df_expanded = df_expanded.drop(columns=['feature_1582'])

In [137]:
df_expanded

feature_0 feature_1 feature_2  feature_3 feature_4 feature_5 feature_6  \
0  1.88E+02  4.00E+00  5.38E-01  -1.63E-04  5.62E-01  3.60E-01  1.86E-01   
1  7.80E+01  1.98E+02  3.29E-01  -7.19E-04  4.02E-01  2.54E-01  9.72E-02   
2  2.80E+02  3.19E+02  3.37E-01  -1.96E-04  3.70E-01  2.22E-01  7.16E-02   
3  2.27E+02  7.00E+00  2.95E-01   3.25E-04  2.45E-01  2.08E-01  5.71E-02   
4  1.85E+02  2.08E+02  6.12E-01   1.50E-04  5.95E-01  4.70E-01  2.95E-01   

  feature_7 feature_8 feature_9  ... feature_1572 feature_1573 feature_1574  \
0  4.31E-01  5.94E-01  2.63E+00  ...    -2.30E-03     1.72E-02     2.13E-02   
1  3.15E-01  1.01E+00  3.33E+00  ...     1.43E-03     6.01E-03     7.87E-03   
2  2.68E-01  6.75E-01  2.97E+00  ...     0.00E+00     0.00E+00     0.00E+00   
3  2.41E-01  3.71E-01  1.84E+00  ...    -2.46E-03     1.04E-02     7.39E-03   
4  5.43E-01  5.06E-01  2.02E+00  ...    -1.52E-03     7.65E-03     9.09E-03   

  feature_1575 feature_1576 feature_1577 feature_1578 feature_1579  \
0     1.95E-02     4.08E-02     1.48E-01     1.97E-02     6.58E-03   
1     4.58E-03     1.24E-02     2.23E-02     1.38E-01     6.90E-02   
2     0.00E+00     0.00E+00     0.00E+00     0.00E+00     0.00E+00   
3     1.29E-02     2.03E-02     1.29E-01     6.17E-02     1.23E-02   
4     9.17E-03     1.83E-02     7.42E-02     1.83E-02     9.17E-03   

  feature_1580 feature_1581  
0     1.30E+01     2.92E+00  
1     3.00E+00     2.06E+00  
2     0.00E+00     3.40E+00  
3     4.00E+00     3.10E+00  
4     9.00E+00     2.27E+00  

[5 rows x 1582 columns]

In [109]:
# Step 1: Standardize the features
scaler = StandardScaler()
angry_scaled = scaler.fit_transform(df_expanded)

In [133]:
transposed_scale= angry_scaled.T

In [136]:
transposed_scale[0]

array([-0.05423606, -1.71144903,  1.33179661,  0.53332127, -0.09943278])

In [114]:
len(angry_scaled[0])

1582

In [87]:
import numpy as np

In [226]:
df_expanded

feature_0 feature_1 feature_2  feature_3 feature_4 feature_5 feature_6  \
0  1.88E+02  4.00E+00  5.38E-01  -1.63E-04  5.62E-01  3.60E-01  1.86E-01   
1  7.80E+01  1.98E+02  3.29E-01  -7.19E-04  4.02E-01  2.54E-01  9.72E-02   
2  2.80E+02  3.19E+02  3.37E-01  -1.96E-04  3.70E-01  2.22E-01  7.16E-02   
3  2.27E+02  7.00E+00  2.95E-01   3.25E-04  2.45E-01  2.08E-01  5.71E-02   
4  1.85E+02  2.08E+02  6.12E-01   1.50E-04  5.95E-01  4.70E-01  2.95E-01   

  feature_7 feature_8 feature_9  ... feature_1572 feature_1573 feature_1574  \
0  4.31E-01  5.94E-01  2.63E+00  ...    -2.30E-03     1.72E-02     2.13E-02   
1  3.15E-01  1.01E+00  3.33E+00  ...     1.43E-03     6.01E-03     7.87E-03   
2  2.68E-01  6.75E-01  2.97E+00  ...     0.00E+00     0.00E+00     0.00E+00   
3  2.41E-01  3.71E-01  1.84E+00  ...    -2.46E-03     1.04E-02     7.39E-03   
4  5.43E-01  5.06E-01  2.02E+00  ...    -1.52E-03     7.65E-03     9.09E-03   

  feature_1575 feature_1576 feature_1577 feature_1578 feature_1579  \
0     1.95E-02     4.08E-02     1.48E-01     1.97E-02     6.58E-03   
1     4.58E-03     1.24E-02     2.23E-02     1.38E-01     6.90E-02   
2     0.00E+00     0.00E+00     0.00E+00     0.00E+00     0.00E+00   
3     1.29E-02     2.03E-02     1.29E-01     6.17E-02     1.23E-02   
4     9.17E-03     1.83E-02     7.42E-02     1.83E-02     9.17E-03   

  feature_1580 feature_1581  
0     1.30E+01     2.92E+00  
1     3.00E+00     2.06E+00  
2     0.00E+00     3.40E+00  
3     4.00E+00     3.10E+00  
4     9.00E+00     2.27E+00  

[5 rows x 1582 columns]

In [218]:
new_features_pca= df_expanded.iloc[1].to_list()

In [219]:
# Convert the list to a numpy array
new_features_array = np.array(new_features_pca).astype(float)  # Convert to float if necessary

# Reshape to a 2D array with 1 row and n columns (1500 features in this case)
new_features_array = new_features_array.reshape(1, -1)

# Step 1: Standardize the input features (if necessary)
new_features_scaled = scaler.transform(new_features_array)


# Step 2: Apply PCA transformation (if PCA was used during training)
# new_features_pca = pca.transform(new_features_scaled)

c:\Users\T100248\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [220]:
type(new_features_scaled)

numpy.ndarray

In [221]:
new_features_scaled

array([[-1.71144903,  0.41216499, -0.72973554, ...,  1.97385433,
        -0.60583925, -1.36351921]])

In [222]:
new_features_scaled = new_features_scaled[:, :90]

In [223]:
new_features_scaled

array([[-1.71144903,  0.41216499, -0.72973554, -1.67605345, -0.25435866,
        -0.49232788, -0.49697396, -0.39676449,  1.76550869,  1.37512042,
        -0.83179531, -1.0113456 , -0.70475225, -0.76245568, -0.34184956,
        -0.55025722,  0.05400907, -0.2526025 , -0.25329025, -0.5334121 ,
        -0.79575422, -0.54336381, -0.05159969, -0.98121385,  1.03475279,
        -1.11208446,  0.57375657,  0.38682288,  0.37414976,  1.24762737,
        -1.22061021, -1.48479244, -0.81212453, -0.65156821,  1.37683125,
         1.14860786,  1.35596005, -0.37463432, -0.38133879, -0.33328883,
        -1.03625552, -0.47098605, -0.53800834, -0.46827677,  0.54068791,
         0.43739145, -0.2877815 ,  0.11925814, -0.1998835 , -0.27672665,
         0.80696136, -0.72301863, -0.57541797,  0.48695325,  0.34746366,
         0.67652896, -0.13578353,  0.48612691,  0.88241087, -0.34137699,
        -0.70111604,  0.23362836,  0.91310421, -1.58689718, -0.9852302 ,
         0.51449368, -1.74553529,  1.05033588, -1.0

In [224]:
prediction = classifier.predict(new_features_scaled)

In [225]:
prediction

array(['sadness'], dtype='<U9')